### ISSUE TITLE
Remove slowCheck (dirty checking in fixed time intervals)

### ISSUE THREAD

**Issue by warpech** [Starcounter-Jack/JSON-Patch#103]
Remove `slowCheck` (dirty checking in fixed time intervals).

From now on, dirty checking should be only triggered on DOM events (`fastCheck`).

**Comment by tomalec** [comment]
Then users could use `generate` method to check after their changes. 
As for example proposed for PuppetJs https://github.com/PuppetJs/PuppetJs/issues/29#issuecomment-170904351

**Comment by warpech** [comment]
@aloscha please write better Git commit messages. And always write a summary as a comment before closing an issue. The above messages tell me nothing. I cannot even say if the issue was solved or reverted?

**Comment by warpech** [comment]
http://chris.beams.io/posts/git-commit/
