### ISSUE TITLE
Test fails with undefined property

### ISSUE THREAD

**Issue by aloscha** [Starcounter-Jack/JSON-Patch#105]
Two tests fails with `undefined` as a default property.
First test:
       it('`undefined` property is set to something', function() {
          var obj = {foo: undefined};

          var observer = jsonpatch.observe(obj);
          obj.foo = "something";

          var patches = jsonpatch.generate(observer);
          expect(patches).toEqual([{op: 'replace', path: '/foo', value: "something"}]);
        });

IMHO there need to be 'add' instead of 'replace'

Second test:

      it("should generate remove when `undefined` property get removed", function(){
        var obj = {foo: undefined};

        var observer = jsonpatch.observe(obj);
        delete obj.foo;

        var patches = jsonpatch.generate(observer);
        expect(patches).toEqual([{ op: 'remove', path: '/foo' }]);
      });

Here JSON-Patch create empty array as a result.

Also In that task needs to refactor readme:
>README says: "We treat undefined as any other falsy value, and
>implementation & tests works: "We tread undefined as no property specified"

@tomalec, @warpech what guys do you think about it?

**Comment by tomalec** [comment]
There are [many issues related to `undefined`](https://github.com/Starcounter-Jack/JSON-Patch/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+undefined)

Some time ago I have tried to add support for `undefined` as any other falsy value, but it seems it no longer works this way.

If i's to hard to fix JSON-Patch to work that way once again, I would re-describe applicable test cases, and add note on README what is the current behavior - make README in sync with spec.

**Comment by warpech** [comment]
Also, in NodeJS test case 13 tests fail:

<img width="970" alt="screen shot 2016-05-31 at 10 22 32" src="https://cloud.githubusercontent.com/assets/566463/15668055/9c7f3f36-2719-11e6-8d7c-e5eb9947c681.png">

**Comment by aloscha** [comment]
@warpech that happens before https://github.com/Starcounter-Jack/JSON-Patch/pull/104 ?

**Comment by warpech** [comment]
> @warpech that happens before #104 ? (I mean it's happens because changes in that task occurs)?

Yes

**Comment by aloscha** [comment]
@warpech I fixed that, by start using `jsdom`. Now node test returns only 2 errors (the same like in `SpecRunnerDuplex.html`)

**Comment by warpech** [comment]
Thanks @aloscha

**Comment by aloscha** [comment]
>If i's to hard to fix JSON-Patch to work that way once again, I would re-describe applicable test cases, and add note on README what is the current behavior - make README in sync with spec.

Ok, waiting for that

**Comment by warpech** [comment]
Back to the original subject - first of all, we should stop using Jasmine's method `toEqual`, **because it thinks the following statement is correct**:

```js
expect({a: undefined}).toEqual({});
```

Secondly, I propose to use the following approach. `jsonpatch.generate` should treat *undefined* exactly the same way it is treated in `JSON.stringify` and `jsonpatch.compare`.

Every test should go the following path:

    var a = /*some object*/;
    observe(a);
    a.change = /*new value*/;
    var patches1 = generate(a);

    var b = (same object);
    var c = clone(b);
    b.change = /*new value*/
    var patches2 = jsonpatch.compare(b, c);

    expect(patches1).toReallyEqual(/*expected patch*/);
    expect(patches1).toReallyEqual(patches2);

The following commit implements that: https://github.com/Starcounter-Jack/JSON-Patch/commit/ffaa563c0fa667c9dbacc918f17960830b7284af

@tomalec WDYT?

**Comment by warpech** [comment]
I created a pull request. This is a breaking change for undefined. 

@tomalec, @miyconst, @aloscha could you please review the PR? There is a chance that I have overlooked some problem, so please be very critical :)

**Comment by warpech** [comment]
Changes are now merged to master.
