### ISSUE TITLE
Authorize travis-ci

### ISSUE THREAD

**Issue by tomalec** [Starcounter-Jack/JSON-Patch#108]
I'd like to add Travis-CI to automatically and continuously test our changes and PRs.

@Starcounter-Jack in your spare time, could you please authorize https://travis-ci.org to observe this repo?
It seems I do not have privileges.

First you need to grant GitHub aacess to it, then at https://travis-ci.org/profile/Starcounter-Jack you need to enable the switch for this repo.

**Comment by MarkHerhold** [comment]
@tomalec Does it make sense to move this repo and some of the other JSON-Patch related projects into a new org?

**Comment by tomalec** [comment]
Travis authorized, builds are running https://travis-ci.org/Starcounter-Jack/JSON-Patch/builds/184506368

@MarkHerhold We discussed it few times,  but we still don't have any consensus.
Needless to say we cannot find a good name ;)

Feel free to open separate issue about that if you think it is still valid.
