### ISSUE TITLE
Please Publish 1.0.0

### ISSUE THREAD

**Issue by MarkHerhold** [Starcounter-Jack/JSON-Patch#112]
Just a friendly reminder to publish to npm and bower. Cheers on 1.0.0! 🎉 
`npm view fast-json-patch`

Ping @joozek78 @Starcounter-Jack

**Comment by joozek78** [comment]
I'm new to the project, so I don't have permissions yet, but @warpech will take care of it.
BTW thanks for the notice!

**Comment by warpech** [comment]
Done, thanks for noticing it so fast :)
