### ISSUE TITLE
Consider changing root operations behavior

### ISSUE THREAD

**Issue by tomalec** [Starcounter-Jack/JSON-Patch#113]
To continue discussion started at https://github.com/Starcounter-Jack/JSON-Patch/issues/106#issuecomment-227658338

Briefly my idea is that root operations (replace, remove, add) should not copy the object into existing one, but rather replace it completely (at https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch-duplex.ts#L158-L162 and https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch-duplex.ts#L166-L171)

**Comment by tomalec** [comment]
[@joozek78 wrote](https://github.com/Starcounter-Jack/JSON-Patch/issues/106#issuecomment-227673888)
> AFAIK we can't lose the root object, because outside things can reference it. That's why all its properties are changed instead of simple assignment

**Comment by tomalec** [comment]
[@tomalec wrote](https://github.com/Starcounter-Jack/JSON-Patch/issues/106#issuecomment-227697247)

That's the thing, we are replacing the object with new one. So outside things are referencing the old one, not the new one. I suppose that when you are replacing, adding, removing a root element, you mean it - to really use new one, and forget about the old one. Otherwise you would do replace all the properties.
  
 As for 
 ```js
var newObj = {n: 'smth'};
var tree = {prop: {nested: 'value'}};
```
 - to replace `prop` with `newObj` you should do: 

   ```js
{op: 'replace', path: '/prop', value: newObj`}
```
  then `tree.prop === newObj`
 - to replace `prop.nested` with `smth` you do 

   ```js
{op: 'replace', path: 'prop/nested', value 'smth'`}
```

 Why it should behave differently for root obj? 

 I propose that

 - to replace `tree` root with `newObj` you should do: 

   ```js
 {op: 'replace', path: '', value: newObj`}
```
  then `tree === jsonpatch.apply(tree, [operationObj])[0]`, we stopped observing `tree`, and we are now observing `newObj`, and the `newObj` is the one you should now refer to.
 - to replace `tree.prop` with `smth` you do 

   ```js
{op: 'replace', path: 'prop', value 'smth'`}
```
 - to remove `tree.prop` and add `n: 'smth'` you do 

   ```js
[{op: 'remove', path: '/prop'}, {op: 'add', path: 'n', value 'smth'}]
```

However, now, I see that's probably a discussion for 2.0.0 or 1.1.0 at least.

**Comment by alshakero** [comment]
This is implemented in https://github.com/Starcounter-Jack/JSON-Patch/pull/167. Now root can be replaced.
