### ISSUE TITLE
Reference in package.json causes difficulties for ts compiler

### ISSUE THREAD

**Issue by schwer** [Starcounter-Jack/JSON-Patch#114]
The reference to "main" in package.json lacks an extension. This causes issues for those (me) using a typescript compiler because the IE8 shim breaks the 'window' strong typing.

I'd prefer to import the .js file instead, but the default behavior of typescript compilation will resolve the .ts file before it resolves to the .js file.

Generally, I've seen that most other project export the .js file in the package.json instead.

**Comment by schwer** [comment]
See https://github.com/Starcounter-Jack/JSON-Patch/pull/115

**Comment by tomalec** [comment]
Thanks for the feedback and PR :+1:
