### ISSUE TITLE
fast-json-patch unusable with node-inspector

### ISSUE THREAD

**Issue by ugieska** [Starcounter-Jack/JSON-Patch#117]
I'm trying to use fast-json-patch in my webserver. As happens quite often, errors occur, and I usually debug them using node-inspector.

However, node-inspector simply won't work with fast-json-patch. The error I get is this:

`Network.loadResourceForFrontend failed.
Error: ENOENT: no such file or directory, open '/path/to/node_modules/fast-json-patch/src/json-patch-duplex.js.map'`

Is there a way to fix this so that node-inspector will not crash?

**Comment by MarkHerhold** [comment]
I don't think this module has anything to do with your generated .map
files.

**Comment by ugieska** [comment]
It is the job of whoever minified/transpiled the code to generate the source map file. That would be you, or someone else who maintains this module.

If there is no source map file, then you need to remove the comments that claim there is one. These comments are found at the bottom of `json-patch.js` and `json-patch-duplex.js` (they are the last lines of those files).

**Comment by tomalec** [comment]
Seems link regression of https://github.com/Starcounter-Jack/JSON-Patch/issues/55 @ugieska are you fine with removing this link at all? (especially from non-minified versions)

**Comment by tomalec** [comment]
```
//# sourceMappingURL=json-patch-duplex.js.map
```
Was removed in [1.0.1](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.0.1)

Feel free to reopen in case you do not like such solution.
