### ISSUE TITLE
Creating "check" ops

### ISSUE THREAD

**Issue by isaacdcm** [Starcounter-Jack/JSON-Patch#118]
Is it possible to have the functionality that builds the list of diffs output "check" operations at the beginning to ensure that the items to be modified are actually there?

The reason I want to do this is because I may end up with some 3 - way merge operations and would like to be able to catch them easily only if there is a conflict.
Thanks,
Isaac

**Comment by MarkHerhold** [comment]
Are you aware of the [test operation](https://tools.ietf.org/html/rfc6902#section-4.6)? 

The test operations automatically get run on `apply()`.

**Comment by tomalec** [comment]
I would also suggest what @MarkHerhold mentioned above. 
As that is the JSONPatch-way to do it.

However, there we also support undocumented, internal `_get` operation. So you can do: `var obj2 = jsonpatch.apply(obj, [{op: "_get", "path": "/foo"}]);`. You can also use any other simple JSON Pointer getter.

**Comment by isaacdcm** [comment]
Is the best way to put this all together to have a loop go through the returned patch, identify the paths being modified, do a _get or similar call, and then prepend the patch step with a "test" operation?

**Comment by tomalec** [comment]
Do you need to check if the modified node has a specific value, or just check if there is any value at all?

**Comment by isaacdcm** [comment]
A specific value.  What I want to accomplish is the following.  Say 2 users both download a JSON file at the same time.
They both make edits in different parts of the file and upload their results.
On the client side (the one using JSON-Patch) I want to capture the previous value that was in the data structure prior to the change.

On the server side, I want to check that value prior to patching the "master" and if it matches just apply the patch, if not, then reject it with a relevant message about a conflict.

This would allow for multiple people to edit a single JSON structure simultaneously as long as they dont both try to edit the same value at the same time.

**Comment by tomalec** [comment]
Have you treid PuppetJS or JSON Patch OT? 
[PuppetJS](https://github.com/PuppetJs/PuppetJs) is a library made also by our team to handle asynchronous, distributed, real-time collaboration on JSON documents using JSON Patches. It solves the problem you described for you.

[JSON Patch OT](https://github.com/PuppetJs/JSON-Patch-OT-agent) is a piece of underlying tech/science it simple.

Here you have my talk about how it briefly works https://www.youtube.com/watch?v=bTG7pIyzr7A

And the issue related to Operational Transformations https://github.com/Starcounter-Jack/JSON-Patch/issues/57

**Comment by tomalec** [comment]
I'm closing it as answered. Feel free to re-open if you have anything else to add.
