### ISSUE TITLE
If observe() callback function is used, generate() returns no patches 

### ISSUE THREAD

**Issue by sandrokeil** [Starcounter-Jack/JSON-Patch#119]
Let's start with an example:

``` js
var diffObserver = jsonpatch.observe( _formData, function( patch ) {
    console.log(patch);
} );

// later in save()
self.save = function() {
    // patches is empty
    var patches = jsonpatch.generate(diffObserver); 
}
```

The problem is, that the callback function tracks every change, but if you set a value and remove it again, two patches (add and remove) are registered through the callback function, but nothing has changed. I need to know if something has changed, but only want the result of the changes and not every history of the changes. 

Why returns `generate` no patches, if a callback function is used? Tested with version 1.0.0.

A workaround is to use `compare`, but I'm not quite happy with that.

**Comment by tomalec** [comment]
Sorry, but I don't quite get it.
In your code example there is no change being made. Even if there are add+remove of the same node, the result of `generate` will show you the result of those two changes - noting changed - no patches.

Could you provide jsfiddle with an example?

**Comment by sandrokeil** [comment]
Ok, maybe I've a bug in my code. I will check this, but it could take some days. Thanks.

**Comment by tomalec** [comment]
I'm closing it. Feel free to re-open, once you will be able to reproduce it.

**Comment by NicolasLiveris** [comment]
Hi !

I was able to reproduce the problem in a stackblitz. This one is exactly as @sandrokeil described it.

https://json-patch-observe-issue.stackblitz.io

Thank, for help.

**Comment by alshakero** [comment]
Maybe we need to document this but when you pass a callback to observe `generate` will not work anymore since you're getting interim changes.

If you want to use `generate` you may remove the callback from `observe` and it will work as expected.

**Comment by NicolasLiveris** [comment]
Hi, @alshakero 

So if I want to use the callback I have to generate the patch myself?

Thanks.

**Comment by NicolasLiveris** [comment]
That's understood. Thank you for those clarifications and for your time.

**Comment by alshakero** [comment]
My pleasure!

**Comment by alshakero** [comment]
Worth mentioning that the callback will always give you an array (a patch, not a single operation).
