### ISSUE TITLE
Extra globals are leaked

### ISSUE THREAD

**Issue by dcherman** [Starcounter-Jack/JSON-Patch#120]
In addition to the expected `jsonpatch` global that's created, it looks like the dist file generates two additional globals that it shouldn't:

`["__extends", "OriginalError"]`

**Comment by tomalec** [comment]
Good catch, thanks for reporting. I'll fix it in upcoming version.

**Comment by tomalec** [comment]
Fixed in [1.0.1](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.0.1)
