### ISSUE TITLE
Running validateSpec.js, Unit tests

### ISSUE THREAD

**Issue by MarkHerhold** [Starcounter-Jack/JSON-Patch#121]
I'm trying to run the tests in prep for PR'ing a change and there doesn't seem to be anything that actually runs the `validateSpec.js` tests. I see the test file is referenced in some of the HTML runners but when I purposefully cause a `validateSpec.js` test to fail I don't get any errors in the console.

Also, some tests fail out of the box.

![image](https://cloud.githubusercontent.com/assets/4934732/18413730/6cdfb9fc-777f-11e6-88b7-2ad58a0cd4e6.png)

Please advise. Thanks.

**Comment by MarkHerhold** [comment]
Ping @tomalec 
Could you advise on this?

**Comment by tomalec** [comment]
My advice would be to run HTML runners for now http://starcounter-jack.github.io/JSON-Patch/test/SpecRunner.html, http://starcounter-jack.github.io/JSON-Patch/test/SpecRunnerDuplex.html

Unfortunately, CLI ones does not work. I've spend entire weekend trying to fix it :| `jasmine-node` is out-dated, but updating it to 2.5 as proposed at http://jasmine.github.io/2.5/node.html does not work either as CLI reporter is broken in Jasmine https://github.com/jasmine/jasmine-npm/issues/88

Sorry for that. If you will find any other way to make jasmine test run in CLI - please let me know. I've just give up and I'm waiting for Jasmine Team to fix that.

**Comment by MarkHerhold** [comment]
Hmm... interesting. These tests look easily port-able to mocha, which I use a lot. I could look into getting that to run as an intermediate solution.

Also, I wrote:
> I see the test file is referenced in some of the HTML runners but when I purposefully cause a validateSpec.js test to fail I don't get any errors in the console.

Can you confirm that test failures are actually displayed in the HTML runners?

**Comment by tomalec** [comment]
We are using mocha in our other projects as well. So, I would say it's good idea :)

> Can you confirm that test failures are actually displayed in the HTML runners?

If I do purposefully cause a `validateSpec.js` test to fail it is displayed in `/JSON-Patch/test/SpecRunnerDuplex.html`

**Comment by MarkHerhold** [comment]
@tomalec Ah, I see the failing test now, but only in Safari (not in Chrome). That's unfortunate...

**Comment by tomalec** [comment]
Really? and if you try for example 
1. http://starcounter-jack.github.io/JSON-Patch/test/SpecRunner.html
2. Open dev tools (f12), 
2. Put a break point at 28th line of http://starcounter-jack.github.io/JSON-Patch/test/spec/validateSpec.js (ctrl+p 'validateSpec', click on 28th)
3. Reload (f5),
4. type: `error="smth"` to the console
5. Run script (f8)

**Comment by MarkHerhold** [comment]
I was running the tests locally. I was getting CORS and one other error. The benchmark worked just fine in Chrome.

**Comment by tomalec** [comment]
Strange, are you trying to run it via web server or just `file://` (I run it via http server and it works fine.)

**Comment by tomalec** [comment]
@MarkHerhold I made `npm test` work again. 
Can we close this issue, or do you have any more questions?

**Comment by MarkHerhold** [comment]
Let's close. Thanks!
