### ISSUE TITLE
compare does not work for Dates

### ISSUE THREAD

**Issue by danielsimons1** [Starcounter-Jack/JSON-Patch#122]
jsonpatch.compare does not work when comparing objects with dates. If the object1.dateField != object2.dateField the resulting patch list does not contain { op: 'replace', path: '/dateField'... as it should. The reason is that the check at https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch-duplex.js#L352 returns true because `typeof date === 'object'`

**Comment by MarkHerhold** [comment]
You can't really represent Date objects in JSON, which I think is why JSON-Patch doesn't support this.

You could try converting the dates to a UTC string.

**Comment by richardschneider** [comment]
I agree with Mark, dates are evil.  Always use a UTC string

**Comment by tomalec** [comment]
As already stated in https://github.com/Starcounter-Jack/JSON-Patch/issues/86, https://github.com/Starcounter-Jack/JSON-Patch/issues/4 we are not going to support `Date` as it's not a valid JSON value and we would like to keep best performance possible to support things defined in RFC spec.

As stated before you should be able to use UTC string.

**Comment by tomalec** [comment]
If you have any other comments feel free to continue or re-open.
