### ISSUE TITLE
Support for Map and Set

### ISSUE THREAD

**Issue by heruan** [Starcounter-Jack/JSON-Patch#128]
I noticed that the observer does not keep track of modification in JavaScript `Map` and `Set` objects. It would be useful to be able to add a callback to handle special types like these!

**Comment by tomalec** [comment]
We are targeting for fastest possible JSON Patch implementation. `Map` and `Set` are not valid JSON objects. So, I don't think your problem should be solved by this library, unless `fast-json-patch` missed modifications in JSONified version of your JS object (`JSON.parse(JSON.stringify(jsObj))`).

I believe patching JS object would be definitely awesome feature. However, I'm affraid

1. We will not have much resources to implement and maintain it,
2. It would me much slower that simple JSON version,
3. We will need complete RFC or any other spec that describes all the custom object specific cases.

**Comment by warpech** [comment]
Closing as this idea was reviewed and dismissed in PR #198 for the following reason:

The goal of `fast-json-patch` is to be the fastest JSON-Patch implementation in JavaScript. This comes with the price of reduced compatibility. We cut corners such as assuming strict JSON compatibility in the observed objects.
