### ISSUE TITLE
Compare function doesn't produce any patches when dates differ

### ISSUE THREAD

**Issue by charlieamer** [Starcounter-Jack/JSON-Patch#130]
The following code shows what I am talking about:
```javascript
var fastjsonpatch = require("fast-json-patch");
a = {test: new Date()};
tmp = new Date();
tmp.setYear(2000);
b = {test: tmp};
console.log(fastjsonpatch.compare(a,b));
```
The code above right now produces 
```json
[]
```
But it should produce
```json
[{"op": "replace", "path": "/test", "value": ...}]
```

**Comment by MarkHerhold** [comment]
Duplicate of https://github.com/Starcounter-Jack/JSON-Patch/issues/122

**Comment by tomalec** [comment]
@charlieamer If there is anything more you would like to discuss, feel free to re-open #122 and continue there.
