### ISSUE TITLE
ES6 module export

### ISSUE THREAD

**Issue by Toub** [Starcounter-Jack/JSON-Patch#132]
Is it planned to be webpack compatible?

**Comment by MarkHerhold** [comment]
I use it with webpack just fine...

**Comment by Toub** [comment]
After a npm install, I got the following error when importing the library:

```ts
import { jsonpatch } from 'fast-json-patch';
```
```bash
(8,27): error TS2307: Cannot find module 'fast-json-patch'.
```
I tried to remove and re-install the npm module twice in case it was corrupted, but it is probably something related to the module declaration.

Maybe not related to webpack, I am using node v6.9.1, npm 3.10.8, typescript 2.0.2 and webpack 2.1.0-beta.20

**Comment by MarkHerhold** [comment]
@Toub jsonpatch it's just

```js
import jsonpatch from 'fast-json-patch';
```

**Comment by Toub** [comment]
Ok, so the problem is not related to webpack, but to the ES6 module syntax my project is using. 

ES6 module syntax:
```
import { jsonpatch } from 'fast-json-patch';
```

CommonJS:
```
import jsonpatch from 'fast-json-patch';
```

RequireJS:
```
var jsonpatch = require('fast-json-patch');
```

So until json-patch is ES6 compatible, I will be using RequireJS syntax:

```
var jsonpatch = require('fast-json-patch');
```

Thanks for your help.

**Comment by Toub** [comment]
Related to #111

**Comment by tomalec** [comment]
Please try [1.1.4](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.1.4)

**Comment by Toub** [comment]
Still the same error:


``` ts
import { jsonpatch } from 'fast-json-patch';

```

``` bash
error TS2307: Cannot find module 'fast-json-patch'.
```

**Comment by tomalec** [comment]
@alshakero Could you take a look?

**Comment by alshakero** [comment]
@tomalec yes, I am aware of this and that's why I suggested grunt-ts. Today I'll try to give you the final answer of it's needed or there is another way.

**Comment by warpech** [comment]
Btw. @alshakero could you pls add release notes for 1.1.4?
