### ISSUE TITLE
Generated patch contains array `length`

### ISSUE THREAD

**Issue by warpech** [Starcounter-Jack/JSON-Patch#14]
In native Object.observe version (Chrome 28 & 30), array `length` is reported as part of the change records.

I don't think this is an error in Chrome, but I think JSON-Patch should filter out `length` from it's own generated patch

See http://jsfiddle.net/U4mZJ/3/

For a sample array, generated patch is:

```
[
 {"op":"replace","path":"/0","value":99},
 {"op":"add","path":"/2","value":3},
 {"op":"replace","path":"/length","value":3}
]
```

I will fix this soon

**Comment by tomalec** [comment]
It seems that such behavior is not a bug in Chrome, but desired behavior for `Object.observe` it's even mentioned in [spec](http://arv.github.io/ecmascript-object-observe/#examples-array).

That's the main difference with `Array.observe`, which I believe we should use for array(-like) nodes.

**Comment by tomalec** [comment]
I'll clean our `.length` logic at https://github.com/Starcounter-Jack/JSON-Patch/commit/0552ac695bb007d3f488ad4c91c3dc7aa217bb47. So users may use 'length' property name for non-array objects. For arrays, we will handle `splice` change type.
