### ISSUE TITLE
Summation of Patches

### ISSUE THREAD

**Issue by suni-masuno** [Starcounter-Jack/JSON-Patch#143]
Is it possible, or reasonable, to take an array of patches and sum them into a final set of patches without an original document? 

example...
```
[
{ "op": "add", "path": "/a/b/c", "value": 1},
{ "op": "replace", "path": "/a/b/c", "value": 12 },
{ "op": "replace", "path": "/a/b/c", "value": 123 },
{ "op": "replace", "path": "/a/b/c", "value": 1234 },
{ "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
{ "op": "replace", "path": "/a/b/d", "value": 12345 },
]
```
and sum it to the actual final modification
```
[
{ "op": "add", "path": "/a/b/d", "value": 12345 },
]
```

Would this be a feature request?
NOTE: I could apply then compare to recreate this, but I'm interested in doing it without an original.

**Comment by tomalec** [comment]
That's a really great idea, we already faced similar concerns many times. But in favor of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy), I'd rather see it as separate tool like "JSON-Patch compresor"/"optimizer", so you could do:
```js
let compressedPatch = jsonpatch.compress(patch, tree);
jsonpatch.apply(tree, compressedPatch);
```
This compression could take an **optional** argument `tree` as a context optimize even more, but probably in more expensive manner.

//cc @alshakero

**Comment by alshakero** [comment]
I agree with the linux way too. I'll close this as out of scope. 

---

Feel free to check https://github.com/Starcounter-Jack/JSON-Patch/issues/204#issuecomment-394110124.
