### ISSUE TITLE
Remove TS code and add Typings

### ISSUE THREAD

**Issue by alshakero** [Starcounter-Jack/JSON-Patch#146]
After our discussion regarding PuppetJS, it makes sense to apply the same arguments and remove TS code and keep a maintained `typings` file for TS users.

@warpech WDYT?

P.S: I consulted @tomalec already.

**Comment by felixfbecker** [comment]
Apparently the TypeScript source was only recently added to the NPM package, this broke our builds. TypeScript source should never be in NPM packages, only the compiled .js and .d.ts.
A .gitignore should ignore .js and .d.ts (the dist folder), a .npmignore should ignore the .ts files (the src folder)

**Comment by alshakero** [comment]
@felixfbecker the source was always there, only `typings` config was added to `package.json`. This applied your `tsconfig` config on the code and caused the issue. I'll fix this ASAP.

**Comment by felixfbecker** [comment]
@alshakero thanks for the quick response, I realised now the `typings` property is the culprit. Could you take a look at #148? That should fix it and improve the setup overall
