### ISSUE TITLE
Better TS typing

### ISSUE THREAD

**Issue by felixfbecker** [Starcounter-Jack/JSON-Patch#150]
Atm many params are typed `any`. There are good (not perfect) typings here: https://github.com/types/npm-fast-json-patch/blob/master/index.d.ts

Would be great to integrate these into the TS source.

**Comment by MRamos62786** [comment]
What about this one:
https://github.com/MRamos62786/DefinitelyTyped/blob/3adb314ef365eb93b94babaf972a90793386c377/types/fast-json-patch/index.d.ts

I got it into the DefinitelyTyped repo but the typings for this module were removed with:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15645

**Comment by felixfbecker** [comment]
@MRamos62786 those look good! Care to do a PR to integrate them?

**Comment by MRamos62786** [comment]
@felixfbecker, I've submitted https://github.com/Starcounter-Jack/JSON-Patch/pull/164.

**Comment by alshakero** [comment]
@felixfbecker good to close? I think @MRamos62786 nailed it.
