### ISSUE TITLE
JSON diff on arrays

### ISSUE THREAD

**Issue by hanouard** [Starcounter-Jack/JSON-Patch#152]
Hello,

I'am using JsonPatch.compare on 2 objects with array and the calculated diff doesn't ignore the order on the 2 arrays. 

Example:
`Obj1 = {list:[{arch: 'x64', arch:'x86'}]}`

`Obj2 = {list:[{ arch:'x86', arch: 'x64'}]}`

My expected result: `diff=[]`
Since i only changed the order and the content is the same.

Is there a hidden option to enable this kind of behavior?

**Comment by alshakero** [comment]
There shouldn't be. Because 
```
{arch: 'x64', arch:'x86'}
```
actually means
```
{arch:'x86'}
```
and 
```
{ arch:'x86', arch: 'x64'}
```
actually means
```
{arch:'x64'}
```

You're using the same key for two values. The second one will override the first.

**Comment by hanouard** [comment]
sorry, i've messed up my example:
`Obj1 = {list:[{arch: 'x64'}, {arch:'x86'}]}`

`Obj2 = {list:[{ arch:'x86'}, {arch: 'x64'}]}`

**Comment by mrenvoize** [comment]
Array order is significant in JSON, quoting [rfc7159](https://tools.ietf.org/html/rfc7159#section-1): 'An array is an ordered sequence of zero or more values.'

**Comment by alshakero** [comment]
@mrenvoize Thanks!

Closing as answered..
