### ISSUE TITLE
Expose `json-patch.js` in the Node module

### ISSUE THREAD

**Issue by alshakero** [Starcounter-Jack/JSON-Patch#154]
After migrating Palindrom to ES6 Proxies. I noticed that we don't use `compare`, `generate` or any `json-patch-duplex.js` functions anymore. Yet, we are bundling its code in Palindrom for nothing, _I guess_.

So we need to allow NPM users to choose between `json-patch.js`, and `json-patch-duplex.js`. And this unfortunately is a breaking change. If you approve, it would be very simple to do by adding an `index.js` file and exporting both of them. Like [in here](https://github.com/Palindrom/JSON-Patch-Queue/blob/master/src/index.js):

```js
var jsonpatchsimplex = require('./json-patch.js');
var jsonpatchduplex = require('./json-patch-duplex.js');


module.exports = { 
  jsonpatchsimplex: jsonpatchsimplex,
  jsonpatchduplex: jsonpatchduplex,
  /* Babel demands this */
  __esModule:  true
};

```
And point to it as `main` in `package.json`. Done.

This way, we can also log.warn in `fast-json-patch.js` that it is deprecated. 

@warpech, @tomalec WDYT?

**Comment by warpech** [comment]
Is it possible to do `require('fast-json-patch/apply)` in Palindrom?

Like it is done in [lodash](https://github.com/lodash/lodash).

**Comment by alshakero** [comment]
@warpech woah, that's an amazing idea. Executing instantly!

**Comment by alshakero** [comment]
@warpech your comment was like an epiphany. Turns out this works without any change to `fast-json-patch`. 

Like this:
```js
var jsonpatch = require('fast-json-patch/src/json-patch');
```
