### ISSUE TITLE
Cannot find the .ts files

### ISSUE THREAD

**Issue by danieldonev** [Starcounter-Jack/JSON-Patch#156]
I use Ionic 2. When I use npm install, only the js files are retrieved. I think it would be nice to have the .ts files in the /src at least.

After reading the .npmignore i found that there is this '*.ts'. Is there a reason why the .ts files are ignored ?

**Comment by SimonSchick** [comment]
@tomalec can confirm, also DefinetlyTyped just deleted the @types package fixing this would be a good thing.

**Comment by tomalec** [comment]
I think it was by accident. @alshakero recently was making some changes around packages and ts. Unless he has different opinion, I'd say we should add it back.

**Comment by danieldonev** [comment]
I would be really happy if this could be fixed soon. AFAK it requires just a single file change.

**Comment by alshakero** [comment]
A quick vacation pause :)

TS files were removed to follow TS practices according to @felixfbecker in his PR https://github.com/Starcounter-Jack/JSON-Patch/pull/148.

I don't see any harm in putting them back.

**Comment by felixfbecker** [comment]
Thanks for the mention. Indeed this is a best practice, and you shouldn't need them in the npm package. What do you need the TS files for in the npm package?

**Comment by felixfbecker** [comment]
Okay, the issue here is ***not*** that .ts files are not published, the issue is that .d.ts files are not published. https://github.com/Starcounter-Jack/JSON-Patch/pull/159 should fix this.

**Comment by tomalec** [comment]
@alshakero, @felixfbecker Thanks for comments :) I'll merge #159 then

**Comment by SimonSchick** [comment]
When can we expect a publish?

**Comment by tomalec** [comment]
Done, few seconds ago ;)
