### ISSUE TITLE
Getting error "has no exported member 'jsonpatch'."

### ISSUE THREAD

**Issue by danieldonev** [Starcounter-Jack/JSON-Patch#161]
I am trying to use the library in Ionic 3 (AngularJS typescript).
I have opened an issue about the missing *d.ts files, which resulted with new version 1.1.9.
But now when I write ```import {jsonpatch} from 'fast-json-patch';```
I get this error 
 ```
Module '"/Users/danieldonev/Projects/HG/healthguru-app-user/node_modules/fast-json-patch/src/json-patch-duplex"' has no exported member 'jsonpatch'. 
 ```

Am i doing something wrong, or the module is just not compatible with AngularJS typescript?

**Comment by alshakero** [comment]
Just use `import jsonpatch from 'fast-json-patch'`.

**Comment by danieldonev** [comment]
I am closing the issue and leaving the soution for other people with the same problemn.
After brief reading online documentation (duh...) i fund that the right way to import is:
```import jsonpatch from 'fast-json-patch';```
