### ISSUE TITLE
Performing an add on an array instead does replace

### ISSUE THREAD

**Issue by justechn** [Starcounter-Jack/JSON-Patch#162]
I have an array of objects and I would like to add an additional object. At the time I create the operation I don't know the length of the array so I don't add an index in the path.

I setup my operation like this
```
{
      op: 'add',
      path: '/spec/template/spec/containers/0/env',
      value: { name: 'XDEBUG_CONFIG', value: `idekey=XDEBUG remote_host=${ip.address()}` },
    },
```

However when the operation occurs instead of adding to the array the original array is replaced. 

If I add an arbitrarily high number as the index it works fine.
```
{
      op: 'add',
      path: '/spec/template/spec/containers/0/env/100',
      value: { name: 'XDEBUG_CONFIG', value: `idekey=XDEBUG remote_host=${ip.address()}` },
    },
```

It would make more sense if no index is supplied and it's an array it just gets pushed to the end of the array

**Comment by alshakero** [comment]
[As per the standard](https://tools.ietf.org/html/rfc6902#page-18), you have to use `-` as the index. Tested and works as expected. 

You can try this:
```js
import jsonpatch from 'fast-json-patch';

var myobj = { firstName:"Albert", contactDetails: { phoneNumbers: [ ] } };
var patches = [
   {op:"add", path:"/contactDetails/phoneNumbers/-", value: 1  },
   {op:"add", path:"/contactDetails/phoneNumbers/-", value: 1  }
   ];
jsonpatch.apply( myobj, patches );

console.log(myobj);
```

Output:
```sh
{ firstName: 'Albert',
  contactDetails: { phoneNumbers: [ 1, 1 ] } }
```

**Comment by alshakero** [comment]
Closing as answered.
