### ISSUE TITLE
hasUndefined is bad

### ISSUE THREAD

**Issue by felixfbecker** [Starcounter-Jack/JSON-Patch#163]
This function is found in the codebase:

```js
  /**
   * Recursively checks whether an object has any undefined values inside.
   */
  function hasUndefined(obj: any): boolean {
    if (obj === undefined) {
      return true;
    }

    if (typeof obj == "array" || typeof obj == "object") {
      for (var i in obj) {
        if (hasUndefined(obj[i])) {
          return true;
        }
      }
    }

    return false;
  }
```

- there is no `typeof obj == 'array'`. `typeof` an array is `'object'`. You must use `Array.isArray()` (preferred) or `instanceof Array`. This means the function doesn't actually iterate arrays
- `typeof null` is also `'object'`, this is not checked for
- `for in` is slow as it needs to walk the prototype chain. `Object.keys()` is faster
- `for in` is not suitable for iterating arrays because it iterates properties, not elements. `for of`, `forEach()` or `for` should be used.

**Comment by alshakero** [comment]
@felixfbecker would certainly appreciate a PR!

**Comment by alshakero** [comment]
@felixfbecker I'm going for this, I thought I should tell you in case you were about to go for it too.

**Comment by warpech** [comment]
Context: that was added in https://github.com/Starcounter-Jack/JSON-Patch/issues/73

Totally agree with the OP

**Comment by alshakero** [comment]
Closing as fixed.
