### ISSUE TITLE
Replace parseInt with bitwise operation

### ISSUE THREAD

**Issue by felixfbecker** [Starcounter-Jack/JSON-Patch#171]
`~~` or `>> 0` will convert it's input to an unsigned integer and is a lot faster than `parseInt`.

https://jsperf.com/number-vs-parseint-vs-plus/24

**Comment by alshakero** [comment]
I got this: 
![image](https://cloud.githubusercontent.com/assets/17054134/26049802/89375cfa-395c-11e7-8426-48ab74823234.png)

**Comment by felixfbecker** [comment]
In what browser?

**Comment by alshakero** [comment]
Chrome Version 58.0.3029.110 (64-bit)

But I checked the graphs below and it seems like a very very recent enhancement in Chrome.

**Comment by felixfbecker** [comment]
![image](https://cloud.githubusercontent.com/assets/10532611/26049910/07c13c6c-395d-11e7-872d-790c7ab57464.png)

**Comment by felixfbecker** [comment]
Tbh I have a hard time believing that, because `parseInt` needs to handle a lot more cases like exponential notation, negative numbers, hexadecimal notation, octal notation and has the overhead of a function call.

**Comment by alshakero** [comment]
Me too, I'm checking on another machine.

**Comment by alshakero** [comment]
This one agrees ![image](https://cloud.githubusercontent.com/assets/17054134/26050127/d76c1a68-395d-11e7-949f-91f2b68cfdcb.png)

**Comment by alshakero** [comment]
I guess ~~ it is.

**Comment by tomalec** [comment]
I really like to approach of optimizing every single line :) but maybe we should also compare benchmarks of entire `apply`, not to try be smarter than JS engine with micro-optimization?

**Comment by felixfbecker** [comment]
It won't be slower for sure ;) Why go the effort for more benchmarks if the effort to just make the changes is less than that?

**Comment by tomalec** [comment]
> Why go the effort for more benchmarks if the effort to just make the changes is less than that?

What I had in mind is to make the changes, then check using existing benchmarks to be absolutely sure.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter-Jack/JSON-Patch/pull/167.

**Comment by alshakero** [comment]
Maybe ~~ is slow 😆 
https://youtu.be/g0ek4vV7nEA?t=544
