### ISSUE TITLE
Export function to escape pointers

### ISSUE THREAD

**Issue by felixfbecker** [Starcounter-Jack/JSON-Patch#173]
This is currently done inline with `.replace()`, it would be very helpful in applications

**Comment by alshakero** [comment]
You mean this line?

```js
key = key.replace(/~1/g, '/').replace(/~0/g, '~'); // escape chars
```

**Comment by felixfbecker** [comment]
yep. I have written a function that does this + a function that does the inverse in my application and realized it would be easier if fast-json-patch just exported them since it needs them too. Basically `encodeURIComponent` and `decodeURIComponent`, but for JSON Pointers instead of URIs.

**Comment by alshakero** [comment]
This one actually `unescapes` right? Because we already have this:

```js
function escapePathComponent(str) {
    if (str.indexOf('/') === -1 && str.indexOf('~') === -1) return str;
    return str.replace(/~/g, '~0').replace(/\//g, '~1');
  }
```

**Comment by felixfbecker** [comment]
yes, but both would be helpful.

**Comment by alshakero** [comment]
Yes yes, I'm just asking for naming purposes.

**Comment by alshakero** [comment]
Done in https://github.com/Starcounter-Jack/JSON-Patch/pull/167.
