### ISSUE TITLE
Make `applyOperation` a standalone function and use it inside `applyPatch`

### ISSUE THREAD

**Issue by alshakero** [Starcounter-Jack/JSON-Patch#175]
For a cleaner and more concise code, we decided the followed:

1. Create a standalone `applyOperation` function (i.e doesn't call other functions). 
2. Create a new `applyPatch` function that loops on operations and calls `applyOperation`.
3. Export a deprecated `apply`.
4. Add a reducer function `applyReducer` to be used with `Array.reduce`.

@tomalec did I get everything right?

**Comment by felixfbecker** [comment]
Why does the reducer have to be a separate function?

**Comment by alshakero** [comment]
@felixfbecker because `applyOperation` returns a single result of what `apply` returns now. Not the original/result object.

**Comment by alshakero** [comment]
```ts
applyOperation<T>(document: T, operation: Operation): Result;
applyPatch<T>(document: T, patch: Operation[]): Result[];
applyReducer<T>(document: T, operation: Operation): T;
```

**Comment by tomalec** [comment]
@felixfbecker We took your suggestions on our architecture quite seriously and we would like to drop the functionality that [rewrites properties for root operations](https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch.js#L131) and replace the object instead.

Also, we thought it would be convenient to have `applyOperation` - a function that applies single operation object - especially we already have this code, and make current `apply` (alias `applyPatch`) just iterate over `patch` and call `applyOperation`.

We will still need `results` array for our use-cases. For example, to be able to figure out what was removed by n'th operation. Take native `splice` as analogy (for any `op != 'test'`), it returns removed elements, not the given array, modified array, nor added elements - these were given and known on input.

To support `applyOperation` as a reducer, which we find useful as well, we would create a sugar/ helper wrapper for regular method, that will return resulting object.

Please, let us know if you have any comments on that.

**Comment by felixfbecker** [comment]
I think having `applyPatch` just call `applyOperation` makes a lot of sense. But as I understand, if `applyOperation` and `applyPatch` (and the deprecated `apply`) all return a result array, then they will not support replacing the root, correct? If that is true I am worried why we introduce 2 new functions that don't support the full JSON Patch spec + 1 deprecated, but only have one that supports the full spec.

Other JSON Patch implementations solve this by returning an object like `{ document, meta }` that gives you both.

**Comment by alshakero** [comment]
@felixfbecker I guess it was my fault to not explain well. `applyOperation` will indeed work on root 💃 

We decided to handle that in all our libs higher in the stack.

**Comment by alshakero** [comment]
@tomalec I guess I am going for the `{ document, results }` method.

If we want to apply on root, we can't return results. That's why I'll return `{ document, result }` and then

`applyPatch` could use `applyOperation().result` 
`applyReducer `could use `applyOperation().document`

**Comment by felixfbecker** [comment]
I would make `applyPatch` return `{ document, result }` too

**Comment by alshakero** [comment]
@felixfbecker yes that's what eventually happened.

**Comment by tomalec** [comment]
>  then they will not support replacing the root, correct? 
Both will support replacing root object.

I don't think supporting replacing root collides with returning result array.

To be able to support `applyReducer` and to make `results` any usefull for patches that replaces root , `result` simple need to contain `newDocument` reference, so we eventually end up with the conceptually same think as `{document, result} ~= result {removed, newDoc}` :)

**Comment by tomalec** [comment]
So I rather thought about:
- `applyOperation :Result`
- `applyPatch: Result[]`
- `applyReducer: JSON` could use `result = applyOperation(); result.newDocument`

But I guess it's more or less the same thing you proposed/

**Comment by felixfbecker** [comment]
I'm a bit confused, what is the interface of `Result`? What's the benefit of returning an intermediate result for every array item in `applyPatch`, considering without cloning it's the same object reference so it can be the same regardless of mutations?

**Comment by alshakero** [comment]
@felixfbecker `results` is some weird array that you shouldn't worry about. It has nothing to do with JSON patch spec or JSON patch in general. They're used later to notify Polymer about tree modifications. For instance, `add` operation returns nothing (that's what Polymer needs), while `remove` returns the removed object. And `replace` returns the removed object too! You shouldn't really bother trying to understand it. 

But I can tell you that we need it, at least for now :D

**Comment by felixfbecker** [comment]
@alshakero I understand that, but assuming I want to use the `applyOperation` and `applyPatch` API, how would I get the final updated document? That's why I asked about its interface.

**Comment by alshakero** [comment]
I'll document everything. It's `applyOperation().document` and `applyPatch.document`.

**Comment by tomalec** [comment]
```js
let tree = {
    foo: [
        'all'
        {grass: {something: 'deeper'}},
        'cow'
    ]
}
let patch = [
    {op: 'add', path: 'foo/-', value: 'eat'},
    {op: 'move', from: '/foo/1', path: '/foo/3' }
    {op: 'replace', path: 'foo/3/grass', value: 'boo'},
    {op: 'remove', path: 'foo/3'}
]
let outcome = jsonpatch.applyPatch(tree, patch);
```

How would you get the reference to removed `{something: 'deeper'}` object if `outcome` is equal just `tree` and does not return results of intermediate steps? (without applying `jsonpatch.applyPatch(deepClone(tree), patch[0..2]);`)

**Comment by tomalec** [comment]
Sorry my comment above is the answer to https://github.com/Starcounter-Jack/JSON-Patch/issues/175#issuecomment-302355775, as I didn't refresh the page to see your later comments.

**Comment by alshakero** [comment]
Done in https://github.com/Starcounter-Jack/JSON-Patch/pull/167
