### ISSUE TITLE
Copy operation doesn't deep clone, only references

### ISSUE THREAD

**Issue by alshakero** [Starcounter-Jack/JSON-Patch#177]

**Comment by felixfbecker** [comment]
Why is that a problem?

**Comment by tomalec** [comment]
It may be for someone expecting resulting object to be a JSON tree. You cannot use JSON syntax to create reference, you can only create two identical nodes.

```js
let obj = {
  foo: {
    bar: 'baz'
  }
};
jsonpatch.applyOperation(obj, {op: 'copy', path: 'copied', from: 'foo'});
```
at this point your object looks like:
```js
obj:
  foo: {
    bar: 'baz'
  },
  foo: {
    bar: 'baz'
  }
};
```
with current implementation
```
jsonpatch.applyOperation(obj, {op: 'replace', path: 'copied/bar', from: 'buz'});
```
changes also `foo/bar`. Which is pretty confusing as `jsonpatch.applyOperation(JSON.parse(JSON.stringify(obj)), {op: 'replace', path: 'copied/bar', from: 'buz'});` will not.

I think that's a difference between "copy" and "attach"

https://tools.ietf.org/html/rfc6902#section-4.5:
>  This operation is functionally identical to an "add" operation at the
   target location using **the value** specified in the "from" member.

"Value" not "reference".

**Comment by alshakero** [comment]
Closing as fixed in https://github.com/Starcounter-Jack/JSON-Patch/pull/134
