### ISSUE TITLE
1.2.0: Get operation chokes on empty path

### ISSUE THREAD

**Issue by shockey** [Starcounter-Jack/JSON-Patch#178]
Hi everyone,

I help maintain [swagger-client](https://www.npmjs.com/package/swagger-client), which depends on `fast-json-patch` 1.x.x. I was opening a PR today against our repository, and started seeing CI failures even though my local was fine.

I was able to isolate the issue to `fast-json-patch`. 1.1.8 is fine, but 1.2.0 breaks ten tests in our suite that uses `apply`.

Here's a piece of sample code that recreates the issue:

```js
var fastJsonPatch = require("fast-json-patch")
var doc = {}
var patches = [{"op":"_get","path":""}]

fastJsonPatch.apply(doc, patches) // 1.2.0 throws on this call

console.log(doc) // 1.1.8 gives {}
```

Here's the trace:

```
/Users/kyle/swagger/js/node_modules/fast-json-patch/src/json-patch-duplex.js:609
                Object.keys(value_1).forEach(function (key) { return document[key] = value_1[key]; });
                       ^

TypeError: Cannot convert undefined or null to object
    at _loop_1 (/Users/kyle/swagger/js/node_modules/fast-json-patch/src/json-patch-duplex.js:609:24)
    at Object.apply (/Users/kyle/swagger/js/node_modules/fast-json-patch/src/json-patch-duplex.js:617:13)
    at Object.<anonymous>
```

It looks like passing an empty path in the patch is the problem. It appears that `_get` is an internal-ish part of the library, so it might be our fault to be leaning on it.

Let me know what y'all think - I'd be happy to make a PR if you can point me in the right direction.

**Comment by felixfbecker** [comment]
Looks like a bug to me, but FYI there is now `getValueByPointer()` as a public API for `_get`. But it uses `_get` under the hood, so likely affected too.

**Comment by alshakero** [comment]
Thank you for the elaborate reporting! Will get back to you ASAP.

**Comment by alshakero** [comment]
@shockey released 1.2.1! 

FYI, as @felixfbecker has said, please avoid using `_get` operation, it is not part of the API and might be removed or changed without being considered as a breaking change. The correct alternative is [`getValueByPointer`](https://github.com/Starcounter-Jack/JSON-Patch#jsonpatchgetvaluebypointerdocument-object-pointer-string). And it's much cleaner.

Thanks a lot :))

**Comment by shockey** [comment]
@alshakero thanks for the quick turnaround on this! can we get an `npm publish` of this version?

**Comment by alshakero** [comment]
@shockey done.

**Comment by shockey** [comment]
@alshakero, I just pulled down 1.2.1 and I'm seeing the same issue 😕 

Here's my example running against the latest version: https://runkit.com/shockey/593194bafad712001247593c

**Comment by felixfbecker** [comment]
It works for me with `getValueByPointer`

**Comment by alshakero** [comment]
@shockey I was a little hesitant to fix an edge case for a deprecated API. But published 1.2.2 🎊 

I've just noticed that your example isn't correct BTW. If you want to `_get` a value, you should use `patch.value` after you call `apply`. It worked in 1.8.1 because `apply` didn't throw an error and `doc` is already `doc`. Calling apply was, in fact, extraneous in your example.

Here is an example if all possible ways:
https://runkit.com/alshakero/5931aa4204544700129506a3

Please use `getValueByPointer`, I'd appreciate your effort, even more, testing the actual API in the wild.

**Comment by shockey** [comment]
@alshakero thanks for the fix! tests are looking good again in our repository.

I'll open a ticket to refactor the `_get` usage on our end, but we've kinda made our bed with this: all our currently-released versions of swagger-client target [the current major version of `fast-json-patch`](https://github.com/swagger-api/swagger-js/blob/ee420550c55f39525761993d0cf35dbebf7f464d/package.json#L64). I tightened the dependency to `1.1.8` to avoid the deprecation warning for future versions, but our users of existing versions would be in a not-fun situation without this fix being made. We're looking into version locking as a way to avoid this in the future.

Sorry if my example was a bit contrived - I didn't write the code that handles the patching in our repo, but I was the one holding the bag when the tests started failing 😄 

In you're interested in knowing, we construct an object for `fast-json-patch` [here](https://github.com/swagger-api/swagger-js/blob/7678d4075e97d88442d17fe5597148ea49dd4f6b/src/specmap/lib/index.js#L88) in our codebase. `fast-json-patch` 1.2.0 and 1.2.1 caused [this allOf test](https://github.com/swagger-api/swagger-js/blob/7678d4075e97d88442d17fe5597148ea49dd4f6b/test/specmap/all-of.js#L10) to fail, because our [allOf plugin was constructing a `_get` patch with an empty path](https://github.com/swagger-api/swagger-js/blob/7678d4075e97d88442d17fe5597148ea49dd4f6b/src/specmap/lib/all-of.js#L32).

I (along with our OSS team!) appreciate you going the extra mile on this. Cheers! 🍻

**Comment by alshakero** [comment]
More than welcome! Cheers! 🍻
