### ISSUE TITLE
Don't export the whole jsonpatch namespace as default export

### ISSUE THREAD

**Issue by felixfbecker** [Starcounter-Jack/JSON-Patch#181]
Currently, only a `default` export exists, that is a namespace with all the functions. Instead, these functions should rather all be exported directly, without a namespace wrapper around them. This should be possible:
```ts
import { AddOperation, applyOperation } from 'fast-json-patch'
let op: AddOperation
applyOperation(doc, op)
```
but only this works:
```ts
import jsonpatch from 'fast-json-patch'
let op: jsonpatch.AddOperation
jsonpatch.applyOperation(doc, op)
```

**Comment by felixfbecker** [comment]
This would be best solved by writing the source as a proper ES6 module, then wrapping it in a UMD wrapper in a build step.

**Comment by alshakero** [comment]
Closing as fixed in https://github.com/Starcounter-Jack/JSON-Patch/pull/182.
