### ISSUE TITLE
TypeError: obj.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by sgoll** [Starcounter-Jack/JSON-Patch#184]
In certain situations, `compare` fails to calculate a valid JSON patch and throws a `TypeError` with this message instead:

`obj.hasOwnProperty is not a function`

In my case, this happens when running objects created by GraphQL's `graphql` method through fast-json-patch. One location where this error originates is this line in json-patch-duplex.js:

```js
if (obj.hasOwnProperty(key) && !(obj[key] === undefined && oldVal !== undefined && Array.isArray(obj) === false)) {
```

In fact, this error will be thrown whenever custom objects are used that do not have Object in their prototype hierarchy, such as plain maps created with `Object.create(null)`.

I propose to replace all calls to special Object methods with Object.prototype calls such as this:

```js
// Old:
obj.hasOwnProperty(key)
// Replace with:
Object.prototype.hasOwnProperty.call(obj, key)
```

This ensures that no exception is thrown in case objects without the Object prototype are used.

One may certainly argue that this seems like a pretty far-fetched corner case, but e.g. ESLint has a special rule against this type of Object prototype builtins: [Disallow use of Object.prototypes builtins directly (no-prototype-builtins)](http://eslint.org/docs/rules/no-prototype-builtins), see their rationale.

I would be willing to prepare a pull request for the required changes.

**Comment by alshakero** [comment]
Closing as done and [released](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/v2.0.3)! Thank you @sgoll 🎉
