### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by warpech** [Starcounter-Jack/JSON-Patch#189]
Some versions listed in https://github.com/Starcounter-Jack/JSON-Patch/releases do not have release notes

**Comment by alshakero** [comment]
Do I need to write notes for minor fixes like fixing this issue? https://github.com/Starcounter-Jack/JSON-Patch/issues/186

**Comment by warpech** [comment]
Just mention any changes that were made, otherwise, I have no clue if `2.0.4` different from `2.0.3` by 1 bug fix or 100 bug fixes.

**Comment by alshakero** [comment]
Closing as every version now has release notes.
