### ISSUE TITLE
Dates lost with deepClone, results in incorrect patch

### ISSUE THREAD

**Issue by jpillora** [Starcounter-Jack/JSON-Patch#192]
See output in comments below

```js
const jsonpatch = require("fast-json-patch");

let d = new Date();
let obj1 = {field: d};
let obj2 = jsonpatch.deepClone(obj1);

console.log(obj1.field instanceof Date); //true
console.log(obj2.field instanceof Date); //false

console.log(jsonpatch.compare(obj1, obj2).length); // 1
```

**Comment by alshakero** [comment]
Hello!

Sorry but dates are Javascript objects. Not JSON objects. We only support serializable JSON objects, and if you look at the RFC we implement it says:

>  JSON Patch defines a JSON document structure for expressing a
   sequence of operations to apply to a JavaScript Object Notation
   (JSON) document; it is suitable for use with the HTTP PATCH method.
   The "application/json-patch+json" media type is used to identify such
   patch documents.

Thanks.
