### ISSUE TITLE
Compare method giving wrong results

### ISSUE THREAD

**Issue by sachinpachori** [Starcounter-Jack/JSON-Patch#195]
Hi,

I am comparing two states of the same form where in debug mode it is showing 3 values changed however in returned array it is giving 4 values with 3 op = replace and 1 op= add. Don't know why.
Uploaded the images.
Can you please let me know what is the issue?
![image](https://user-images.githubusercontent.com/1555285/34432228-92511f12-ecc9-11e7-8bb7-2501c78e5d9d.png)

![image](https://user-images.githubusercontent.com/1555285/34432156-00c041e0-ecc9-11e7-9adc-ac9ce4f1e255.png)

![image](https://user-images.githubusercontent.com/1555285/34432204-6cba726c-ecc9-11e7-867a-2acb161bdd3f.png)

**Comment by alshakero** [comment]
Hello! It's a little hard to understand the example provided with all those read markings and covered keys. Could you please create a simpler reproduction on jsbin.com? 

I created this boilerplate for you https://jsbin.com/qidoqud/1/edit?html,js,console.

**Comment by alshakero** [comment]
Closing for lack of response from the OP.
