### ISSUE TITLE
jsonpatch.applyReducer will not working with mongoose document

### ISSUE THREAD

**Issue by bhushankumarl** [Starcounter-Jack/JSON-Patch#200]
```
    const params: any = _.merge(req.params, req.body);

    /**
     *  req.body
     *  {
     *     "op":"remove",
     *     "path":"/locations/business"
     *   }
     */
    const patch = [
        {op: params.op, path: params.path, value: params.value}
    ];
    // req.userStore : It is data found through findOne({_id:''}) though mongoose

    console.log('Before ', req.userStore);
    const updatedDocument = patch.reduce(jsonpatch.applyReducer, req.userStore);
    console.log('After ', updatedDocument);
```

My object contains nested object like locations.business.otherProperties

I am trying to remove entire 'locations.business' property from my user object.

But it doesn't work. The output of the Before and After console is exactly same.

Another thing is that when I took the static object instead of `req.userStore : It is data found through findOne({_id:''}) though mongoose` than it works. So it is like it is not working when any variable that uses a fetched object from mongoose.

**Comment by alshakero** [comment]
Hi,

Thank you for reporting the issue, could you please show me what `req.userStore` looks like?

**Comment by bhushankumarl** [comment]
@alex3683 I have resolved the issue.
It was due to the immutable object of the mongoose.

Resolution : 

```
 console.log('Before ', req.userStore);
 const updatedDocument = patch.reduce(jsonpatch.applyReducer, ** req.userStore.toObject() **);
 console.log('After ', updatedDocument);
```
