### ISSUE TITLE
jsonpatch.generate  $$hashKey

### ISSUE THREAD

**Issue by RobinsonSir** [Starcounter-Jack/JSON-Patch#203]
```js
var jsonObj = 
{
	"id": 22,
	"prefix": "0003",
	"name": "DtType-23-1",
	"isMultichannel": true,
	"needCalibrate": false,
	"info": "xa",
	"icon": "",
	"dtTypeEpTypes": [{
		"epTypeID": 1,
		"channelNo": 0
	}, {
		"epTypeID": 7,
		"channelNo": 1
	}]
}
```

I use jsonpatch observer to watch the above `jsonObj`, then i add one obj to `jsonObj.dtTypeEpTypes`,
`jsonObj` like this

```js
jsonObj =
{
	"id": 22,
	"prefix": "0003",
	"name": "DtType-23-1",
	"isMultichannel": true,
	"needCalibrate": false,
	"info": "xa",
	"icon": "",
	"dtTypeEpTypes": [{
		"epTypeID": 1,
		"channelNo": 0
	}, {
		"epTypeID": 7,
		"channelNo": 1
	}, {
		"epTypeID": 1,
		"channelNo": 2
	}]
}
```

Then I use jsonPatch generate function,   get patch operation array below:

```json
[{
	"op": "add",
	"path": "/dtTypeEpTypes/1/$$hashKey",
	"value": "object:231"
}, {
	"op": "add",
	"path": "/dtTypeEpTypes/0/$$hashKey",
	"value": "object:230"
}, {
	"op": "add",
	"path": "/dtTypeEpTypes/2",
	"value": {
                "epTypeID": 1,
		"channelNo": 2		
	}
}]
```

As u can see,  it contains $$hashKey, i don't know why contains that

**Comment by alshakero** [comment]
Hello :) 

Could you please provide more details?

**Comment by miyconst** [comment]
@RobinsonSir 请您说清楚一点，您的问题是什么？

**Comment by RobinsonSir** [comment]
Nobody.......

**Comment by miyconst** [comment]
@RobinsonSir please help us help you:

1. Format the code and the text you write. (See what I did with the main comment).
2. Prepare a [jsfiddle](https://jsfiddle.net/) which demonstrates the problem.

**Comment by alshakero** [comment]
I assume you're using this with Angular. You see angular adds these props to the object for internal diffing. JSON-Patch itself isn't resposible for them not it is adding them.

Your best bet is filter patches and removing angular-added props. Like this:

```js
const patches = [{
	"op": "add",
	"path": "/dtTypeEpTypes/1/$$hashKey",
	"value": "object:231"
}, {
	"op": "add",
	"path": "/dtTypeEpTypes/0/$$hashKey",
	"value": "object:230"
}, {
	"op": "add",
	"path": "/dtTypeEpTypes/2",
	"value": {
                "epTypeID": 1,
		"channelNo": 2		
	}
}]

const filterdPatches = patches.filter(p => !p.path.includes('$$hashKey'));
console.log(filterdPatches);

// filterdPatches
[{"op":"add","path":"/dtTypeEpTypes/2","value":{"epTypeID":1,"channelNo":2}}]

```

**Comment by RobinsonSir** [comment]
Yes, you are right. I use Angularjs ng-repeat with jsonObj.  Now, i remove $$hashkey by myself. Another solution i will try, thanks very much.
