### ISSUE TITLE
Support for JSONPath?

### ISSUE THREAD

**Issue by FreeWillaert** [Starcounter-Jack/JSON-Patch#207]
I'm happy to have found JSON Patch and even happier to find your implementation, but I'm a little disappointed about the JSON Pointer capabilities - especially when it comes to arrays.

Rather than referring to array items by index, I'd like to refer to an item by any unique attribute.

I can't imagine I'm the first to want this, so I wonder: is there a different way to achieve the same result? 
If not, I'm thinking of 
- either forking and adapting JSON-Patch to add (optional) support for JSONPath
- or making a wrapper around JSON-Patch which converts JSONPath to JSON Pointer

Both seem non-trivial though.

Any thoughts on how to tackle this?

**Comment by alshakero** [comment]
Hi, thank you for the nice words!

I think this is out of the scope of this project. This is just an RFC implementation and even JSON-Pointer support that we have is extra sugar. I don't think we'll support JSON-Path, especially given that we mainly focus on performance. 

> Rather than referring to array items by index, I'd like to refer to an item by any unique attribute.

If that's not an example and a real use case then

```js
jsonpatch.getValueByPointer(doc, 'the.path.to.your.array').find(x => x.prop = 'desired-object-prop') // => the object of interest
```

This will be faster than anything we can do, since it's native. I mean the `find` part.

**Comment by FreeWillaert** [comment]
Hi, thanks for your quick response!
Indeed, following your suggestion - with findIndex instead of find - it seems trivial to implement a 'minimal' wrapper that does not support full JSONPath but does allow .../key=value/... paths.
I'll give it a try.

Still hoping for ideas to be able to use full JSONPath though :)

**Comment by Lusito** [comment]
Any success with that? Also looking for this kind of action

**Comment by tomalec** [comment]
I am sorry to say so but given our crave for performance, keeping the library as lightweight as possible, and very limited resources, I don't think we could afford to maintain a new feature not mentioned in RFC.

**Comment by claytongulick** [comment]
I'm tossing around the idea of adding this to: https://www.npmjs.com/package/mongoose-patcher 

If mongoose is your target, and you think this would be useful, maybe we can create an issue and I can add it to the lib.

Using JSON-Patch *a lot* in RESTful apis, I can agree that constantly doing findIndex is a little wearying. If others want/need it, I think I could make it happen pretty fast.
