### ISSUE TITLE
Memory leak when using observe

### ISSUE THREAD

**Issue by arosequist** [Starcounter-Jack/JSON-Patch#208]
[Runnable example](https://jsbin.com/gofesajele/edit?html,output)

If you `observe` an object, I think it stays in memory after all references to it are gone (even if you `unobserve` it).

I'm not certain, but I suspect that the [`beforeDict`](https://github.com/Starcounter-Jack/JSON-Patch/blob/b2d122d83f596312b04bd320f613a9ccc26676b9/src/duplex.ts#L29) is what's holding on to it. When the observer is created, we [`push`](https://github.com/Starcounter-Jack/JSON-Patch/blob/b2d122d83f596312b04bd320f613a9ccc26676b9/src/duplex.ts#L93) onto the array, but we never `splice` it out.

It would be great if we could use weak references in that array, but I don't think that's possible in JavaScript. Can we just splice it in the unobserve function?

**Comment by alshakero** [comment]
Hi! Thanks for reporting this. 

> It would be great if we could use weak references in that array

It is certainaly possible but this library was build before [WeakMaps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) were around. Now even IE11 supports them. 

I'll look into this sometime soon.

**Comment by alshakero** [comment]
PR in https://github.com/Starcounter-Jack/JSON-Patch/pull/212
