### ISSUE TITLE
Improper patch created under certain scenarios

### ISSUE THREAD

**Issue by bozzaj** [Starcounter-Jack/JSON-Patch#209]
Consider the following:

```
var obj1 = { "0": 4 }
var obj2 = [4];
```

jsonpatch.compare() generates an empty patch.

The following also is invalid, related in part to the above:
```
var obj1 = {
    test: [
        { k: "xx" },
        { k: "yy" }
    ]
};

var obj2 = {
    test: {
        "xx": { k: "xx" },
        "yy": { k: "yy" }
    }
};
```

The patch created is:
```
[{
    "op": "remove",
    "path": "/test/1"
}, {
    "op": "remove",
    "path": "/test/0"
}, {
    "op": "add",
    "path": "/test/xx",
    "value": {
        "k": "xx"
    }
}, {
    "op": "add",
    "path": "/test/yy",
    "value": {
        "k": "yy"
    }
}]
```

It seems that the change from object to an array or an array to an object isn't correctly detected.

**Comment by TheGr8Nik** [comment]
With latest version the patch generated for the second case is:

    [{
      "op": "replace",
      "path": "/test",
      "value": {
        "xx": {
          "k": "xx"
        },
        "yy": {
          "k": "yy"
        }
      }
    }, {
      "op": "replace",
      "path": "/test",
      "value": {
        "xx": {
          "k": "xx"
        },
        "yy": {
          "k": "yy"
        }
      }
    }]

It could be ok if only one `replace` action is generated.
