### ISSUE TITLE
Is it realy tested on IE8?

### ISSUE THREAD

**Issue by mort3za** [Starcounter-Jack/JSON-Patch#223]
In the source code I see `new WeakMap()` which is only available in IE11. Also I've tested it on IE9 and it has an error for using WeakMap.

**Comment by alshakero** [comment]
You're right. It would be appreciated if you could PR to fix the README.

**Comment by mort3za** [comment]
I recommend you to generate an es5 version of the library beside current build If you want to keep es6 version (and it's a good idea because it's faster and smaller).

**Comment by alshakero** [comment]
Sorry but we're not willing to maintain support for IE8. We only support IE10+.

**Comment by mort3za** [comment]
IE10+ means included IE10, right?
IE10 don't understand WeakMap :)

Personally I have no problem with or without IE support, because I have included babel-polyfill, But I think supporting more browers leads to fewer hassles for developers.

**Comment by warpech** [comment]
We will fix the readme to say that only IE11 is supported directly. Older browsers can by supported using a transpiling bundler, as @mort3za suggested.
