### ISSUE TITLE
rollup warning, this has been rewritten

### ISSUE THREAD

**Issue by benitogf** [Starcounter-Jack/JSON-Patch#256]
not sure if it's a problem with my rollup config, has anyone seen this warning?

![image](https://user-images.githubusercontent.com/1633813/85486186-bc137800-b5fc-11ea-9c10-f1a1f578151d.png)

**Comment by Starcounter-Jack** [comment]
You could safely ignore that warning. Add the onwarn property to your rollup-config.js file:

```
onwarn: function(warning) {
    // Skip certain warnings

    // should intercept ... but doesn't in some rollup versions
    if ( warning.code === 'THIS_IS_UNDEFINED' ) { return; }

    // console.warn everything else
    console.warn( warning.message );
}
```
