### ISSUE TITLE
Date comparison always yields a patch

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter-Jack/JSON-Patch#4]
Originally described [here](https://github.com/Starcounter-Jack/JSON-Patch/pull/2)

When you do a comparison on an object that includes dates, all dates end up resulting in patches. This is because JSON.parse(JSON.stringify)) is used to generate an internal cache object, but that does not result in an object with identical values. Dates get converted to strings:

``` js
d = new Date();
foo = {x: 10, y: "test", z: d};
jsonpatch.observe(foo);
bar = jsonpatch.observe(foo);
jsonpatch.generate(bar);
```

**Comment by Toub** [comment]
So, how do we generate patches for dates?
Maybe that custom comparison function could help: https://github.com/Starcounter-Jack/JSON-Patch/issues/92
