### ISSUE TITLE
Remove sourceMappingURL Comment

### ISSUE THREAD

**Issue by TigerC10** [Starcounter-Jack/JSON-Patch#55]
I'm compiling all of my JS files into a single file with grunt, and the following line is forcing the browser to attempt to download a file that does not exist:
`//# sourceMappingURL=json-patch.min.js.map`

Manually specifying this in the file is not required, any browser that supports map files will automatically look for them in the same directory.  It's only required if you want to put the map files in a different directory.

**Comment by oleggen** [comment]
How and where?

**Comment by TigerC10** [comment]
@oleggen as of version 0.5.0 there's no longer an issue with sourceMappingURL.

**Comment by oleggen** [comment]
I'm on prepros 5.2.0 and it seems to be the issue here:
http://vetbakfar.co.il/wp/

**Comment by warpech** [comment]
@oleggen sorry but this does not have anything to do with the library hosted in this repository. Perhaps you are searching for Prepros discussion forums: http://discuss.prepros.io/

**Comment by oleggen** [comment]
Ho.  right -thanks :)

**Comment by xiaomao155** [comment]
我也是这种问题 谁能帮帮我

**Comment by TigerC10** [comment]
这是解决

**Comment by gdibble** [comment]
:tada:
