### ISSUE TITLE
apply() only returns result of last operation

### ISSUE THREAD

**Issue by Xiot** [Starcounter-Jack/JSON-Patch#64]
I am using the `test` operation for some optimistic concurrency, and I noticed that the result from the apply method only takes into consideration the last operation.

From RFC-6902

```
   If a normative requirement is violated by a JSON Patch document, or
   if an operation is not successful, evaluation of the JSON Patch
   document SHOULD terminate and application of the entire patch
   document SHALL NOT be deemed successful.

   See [RFC5789], Section 2.2 for considerations regarding handling
   errors when JSON Patch is used with the HTTP PATCH method, including
   suggested status codes to use to indicate various conditions.

   Note that the HTTP PATCH method is atomic, as per [RFC5789].
   Therefore, the following patch would result in no changes being made
   to the document at all (because the "test" operation results in an
   error):

   [
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "test", "path": "/a/b/c", "value": "C" }
   ]
```

Therefore the apply should at the very least return false if any operation fails.
Currently the `result` variable is only ever set and returned.

**Comment by biofractal** [comment]
I too am having trouble getting my 'test' operations to be respected. This issue has been open a while, which surprises me as it would appear that a core principle of RFC-6902 is being violated. To reiterate, according to the spec a sequence of patches should be atomic:

_From RFC-6902_

>If a normative requirement is violated by a JSON Patch document, or if an operation is not successful, evaluation of the JSON Patch document SHOULD terminate and application of the entire patch document SHALL NOT be deemed successful.

This does not appear to be the case as the following test illustrates:

**original document**
```
{ _id: 54f8469f8cf9510a8a2c5edd,                                                           
  stock: 889,                                         
  __v: 0 }    
 ```
 
**patches**
```
[ { op: 'test', path: '/stock', value: 890 }, 
  { op: 'replace', path: '/stock', value: 888 } ]  
```

**result of apply()**
```
true
```                   
**error generated**
```
null                                        
```                                          
**final patched document**
```
{ _id: 54f8469f8cf9510a8a2c5edd,                                                           
  stock: 888,                                         
  __v: 0 }
```

**Comment by warpech** [comment]
When https://github.com/Starcounter-Jack/JSON-Patch/issues/64 is resolved, this issue becomes resolved

**Comment by MarkHerhold** [comment]
I think this can be closed, correct?

**Comment by alshakero** [comment]
Closing as [`applyPatch`](https://github.com/Starcounter-Jack/JSON-Patch#jsonpatchapplypatchtdocument-any-patch-operation-validateoperation-boolean--function--false-operationresultt) (the new `apply`) returns and array of `OperationResult.
