### ISSUE TITLE
reading value at path using jsonpointer

### ISSUE THREAD

**Issue by kdabir** [Starcounter-Jack/JSON-Patch#66]
I am looking for a way, without introducing a new library, to read value at given path using json-pointer notation. Something like `jsonpatch.get(object, "/pointer/to/key") ` to return value at that path.

I know it's really neither  patching's responsibility, nor it's specified anywhere in RFC but if we have such mechanism(method), it can be very useful.

**Comment by tomalec** [comment]
Thanks for the idea @kdabir. We already thought about it with @warpech, as JSON Pointer is another [RFC6901](https://tools.ietf.org/html/rfc6901) to cover, which in fact we somehow implement internally, but we use it in other projects. 
There are few thing to decide:
1. Should we provide it as part of `jsonpatch`, or as isolated micro lib?
2. Should we then use this separated method/lib in `jsonpatch` internals or leave it as it is?
3. How above will affect performance?

**Comment by warpech** [comment]
It is actually implemented internally, but not returned to the caller. This would be the way to use it:
```js
var obj2 = jsonpatch.apply(obj, [{op: "_get", "path": "/foo"}]);
obj2 === obj.foo; //true
```

Not the most beautiful API but is a low hanging fruit

**Comment by kdabir** [comment]
Is `_get` available for external use? I am trying the code by @warpech in our codebase, it doesn't seem to work.

**Comment by tomalec** [comment]
@kdabir , try 
```javascript
var yourObject = {foo: "bar"};
// missing API workaround starts here
var pointer = {op: "_get", "path": "/foo"};
jsonpatch.apply(obj, [pointer]);
pointer.value; // "bar"
```

So as, functionality is already here, and available for external use, but definitely should be exposed nicer.

**Comment by kdabir** [comment]
@tomalec thanks for the code sample, it worked. I was somehow expecting apply to return the object with value.

Regarding your first comment, extracting a mirco-library seems like way to go if that doesn't affect the performance. Otherwise, providing it as methods on jsonpatch also seems okay to me. Ultimately choice is yours based on any other use-cases you might have in mind.

**Comment by warpech** [comment]
Closing as answered. We are not planning further changes to this API right now.

**Comment by alshakero** [comment]
Now you can use [`getValueByPointer`](https://github.com/Starcounter-Jack/JSON-Patch#jsonpatchgetvaluebypointerdocument-object-pointer-string).
