### ISSUE TITLE
Compare to cujojs/jiff

### ISSUE THREAD

**Issue by mrenvoize** [Starcounter-Jack/JSON-Patch#67]
In your readme you compare to a two out of the three other json-patch libraries mentioned on jsonpatch.com. Any chance you could add the third one to the comparison?

**Comment by tomalec** [comment]
Here you have the benchmark test with updated lib versions http://jsperf.com/json-patch-implementations-showdown/7 for 
 - Starcounter-Jack/JSON-Patch
 - bruth/jsonpatch-js
 - dharmafly/jsonpatch.js

@warpech am I correct that this is the one used in screenshot at README.md?

It seems that culijs/jiff use lots of require dependencies, and it's not so straight-forward to use single-liner in jsperf :/ Have anybody seen a minified version somewhere?

**Comment by warpech** [comment]
@tomalec similar, but not exactly the same as the one used in README.md, which was added in commit https://github.com/Starcounter-Jack/JSON-Patch/commit/4a26d9ca3a2c4757380bcd710c82fa49b5959c7e

**Comment by mrenvoize** [comment]
Slow reply, sorry..  thanks for the pointers; never seen jsperf.com before, it's a revelation :)

I'll have a play, but my gut tells me it will yield similar results with this library being way out in front.

**Comment by Akkuma** [comment]
@mrenvoize #81 should resolve this for you

**Comment by warpech** [comment]
Indeed, thanks @Akkuma!

**Comment by mrenvoize** [comment]
Cheers,  still looking great
