### ISSUE TITLE
can I use JSON-Patch for array this way?

### ISSUE THREAD

**Issue by beetaa** [Starcounter-Jack/JSON-Patch#68]
assume that there's an object like:

```
var obj_src = {
  name: "jone",
  city: "Sydney",
  pets: [
    {nickname: "volo", category: "dog", age: "3"},
    {nickname: "wabit", category: "cat", age: "5"},
    {nickname: "moaoaa", category: "tiger", age: "1"},
    {nickname: "gofast", category: "lion", age: "3"}
  ]
}
```

if pets' nickname is unique, can I use patch like ``{op: "replace", path: "/pets[nickname=wabit]/age", value: "9"}`` to alter **wabit**'s age instead using ``{op: "replace", path: "/pets/1/age", value: "9"}`` because sometimes I don't know the array order.

**Comment by Starcounter-Jack** [comment]
No. The JSON Patch behavior is standardized in RFC6902, so I'm afraid we cannot change the way replace patches work.

**Comment by beetaa** [comment]
Thank you Jack, but how about extending RFC6902 some more features? just call ``RFC6902-x``。

**Comment by tomalec** [comment]
I believe we should serve tiny lib that do one job, and do it well and blazing fast ;)
With tiny support of jsonpointer #66, and native `Array.prototype.filter` I would suggest something like
```javascript
var patch = [{op: "replace", path: "/age", value: "9"}];
var cssFilter = function(selector){
 return function(el, index){
   // do some nice CSS selector style filtering, or anything you want
 }
}
jsonpatch.apply( jsonpointer( obj_src, "/pets").filter(cssFilter("[nickname=wabit]")), patch);
```

Or write completely separated concept of JSON-CSS-Pointer (extended https://tools.ietf.org/html/rfc6901), and then use it like

```javascript
var cssPatch = [{op: "replace", path: "/pets[nickname=wabit]/age", value: "9"}];
jsonpatch.apply( obj_src,  jsonCSSSelectorToPointer( obj_src, cssPatch ));
```

**Comment by beetaa** [comment]
wow! nice answer, @tomalec , thank you very much! I completely agree with your points.

**Comment by tomalec** [comment]
@beetaa Could we close this issue? 

Feel free to vote, and comment at #66.
