### ISSUE TITLE
Replacing null returns error

### ISSUE THREAD

**Issue by winduptoy** [Starcounter-Jack/JSON-Patch#69]
@Starcounter-Jack I'm on 0.5.1.

**My object:** `{foo: null}`
**My patch:** `[ { op: 'replace', path: '/foo', value: 'whatever' } ]`
**Returns:** "Cannot perform the operation at a path that does not exist".
**Expected:** `{foo: 'whatever'}`

**Comment by tomalec** [comment]
Thanks for reporting @winduptoy! I'm currently working on fixing entire falsy values approach.

**Comment by tomalec** [comment]
@winduptoy, it should work fine now. It wil be released as https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/0.5.1
I've also added test cases to https://github.com/json-patch/json-patch-tests/pull/17. Once PR will get merged (or rejected) I will merge it to our repo as well.

**Comment by winduptoy** [comment]
:+1:

**Comment by gdibble** [comment]
good fix!
