### ISSUE TITLE
TypeError exception thrown when 'path' is not defined after calling jsonpatch.validate

### ISSUE THREAD

**Issue by docksteaderluke** [Starcounter-Jack/JSON-Patch#74]
A ```TypeError``` exception is being thrown when the ```path``` parameter isn't specified (or misspelled) in a patch. This is handled correctly when the ```op``` and ```value``` parameters aren't specified, but not ```path```.
```
TypeError: Cannot read property 'split' of undefined
at Object.apply (node_modules/fast-json-patch/src/json-patch-duplex.js:548:34)
at Object.validate (node_modules/fast-json-patch/src/json-patch-duplex.js:686:23)
```

For example:
```json
[
  {
    "op"    : "replace",
    "value" : "Not working"
  }
]
```

**Comment by miyconst** [comment]
@docksteaderluke thank you for reporting the issue. It is fixed now.

**Comment by docksteaderluke** [comment]
Great! When can I expect to see this update on NPM? How frequently do you publish changes on NPM? Thanks again!

**Comment by tomalec** [comment]
Thanks for reminding :) we just forgot to `npm publish`. Now, both `0.5.3` and `0.5.4` are available on npm. 
https://www.npmjs.com/package/fast-json-patch for some reason (probably me publishing in wrong order :innocent:)  shows only `0.5.3`, but version `0.5.4` is tagged as latest

**Comment by docksteaderluke** [comment]
Great! Looks good! Thanks!
