### ISSUE TITLE
Strange behaviour! If path don't start with '/'

### ISSUE THREAD

**Issue by knde** [Starcounter-Jack/JSON-Patch#77]
var obj = {firstName: "Albert"};
var patches = [{op: "add", path: "/lastName", value:"Wester"}];
jsonpatch.apply(obj,patches);
obj = {firstName: 'Albert' },lastName:'Wester' }
If path = "lastName"
The result 
{ '0': 'W', '1': 'e', '2': 's', '3': 't', '4': 'e', '5': 'r' }

why?

**Comment by warpech** [comment]
Hi! This is because it is not a correct path and code is optimized for speed, not for validating patches.

To turn on validation, use `true` as the third parameter (`jsonpatch.apply(obj, patches, true);`)

Check out https://tools.ietf.org/html/rfc6901 for the spec of the path value.

**Comment by warpech** [comment]
Oops! Just noticed that such path does not raise an error with validation. Reopening this for fixing

**Comment by MarkHerhold** [comment]
@tomalec This can be closed now. Please do a patch release when you have time! Thanks! 👍

**Comment by tomalec** [comment]
Thanks @MarkHerhold  for support :) 
[1.1.1](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.1.1) released.
