### ISSUE TITLE
Updated add benchmark

### ISSUE THREAD

**Issue by Akkuma** [Starcounter-Jack/JSON-Patch#81]
I added jiff and json8patch. Jiff I ran through browserify. Both I ran through uglifyjs after getting the non-minified browser dist.

http://jsperf.com/json-patch-benchmark/2

**Comment by warpech** [comment]
Very nice! I was hoping they are a little bit faster, though...

Care to update the `replace` benchmark as well? http://jsperf.com/json-patch-benchmark-replace

**Comment by Akkuma** [comment]
http://jsperf.com/json-patch-benchmark-replace/2 has been updated as well now

**Comment by warpech** [comment]
Nice, thanks!
