### ISSUE TITLE
Object.observe is dead

### ISSUE THREAD

**Issue by warpech** [Starcounter-Jack/JSON-Patch#82]
https://esdiscuss.org/topic/an-update-on-object-observe
https://news.ycombinator.com/item?id=10494512

It is a pity that it won't make it to ES7, but we saw it coming.

We will need to remove it from `json-patch-duplex.js` and fall back to dirty checking (which is already used for JS engines other than V8).

Good news is that our dirty checking was more performant in benchmarks, AFAIK. Also, there is benefit in having the same code for all engines.

**Comment by Starcounter-Jack** [comment]
Just as well. It performed rather poorly. Removing the code will reduce our footprint which is always nice.

**Comment by miyconst** [comment]
Dependency on `Object.observe` is now removed and released as `0.5.5`.

**Comment by tomalec** [comment]
Just to note, maybe we could give some feedback for `Object.observe` champion https://github.com/arv/ecmascript-object-observe/issues/25#issuecomment-139693547
