### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by endel** [Starcounter-Jack/JSON-Patch#87]
Hey there!

The last version was published 4 months ago, it would be great to have the last version there!

Thanks

**Comment by NickStefan** [comment]
:+1:

**Comment by tomalec** [comment]
Thanks for reporting, and sorry for the delay.
```
$ npm view fast-json-patch dist-tags
{ latest: '0.5.6' }
```

**Comment by endel** [comment]
:clap: :clap:
