### ISSUE TITLE
Add should throw errors when replacing

### ISSUE THREAD

**Issue by cefn** [Starcounter-Jack/JSON-Patch#89]
Been using fast-json-patch for the networked synchronization of JSON trees. I discovered that an add which overwrites a part of the target tree is not treated as an error, when I believe it should be. 

The semantics of replace would make this same operation valid and explicit, so I believe that attempting to make a replace change using an 'add' operation should be considered invalid. 

Here's a worked example which I believe should throw a validation error, where the client claims to be adding the path /entry, but applying the 'add' patch to the server which already contains an /entry path does not throw an error...

```javascript
var jsonPatch = require("fast-json-patch");

var serverTreeSnapshot = {entry:{Hello:"World"}};
var serverTree = {entry:{Hello:"World"}};

var clientTreeSnapshot = {};
var clientTree = {entry:{Hi:"Globe"}};

var clientTreeChanges = jsonPatch.compare(clientTreeSnapshot, clientTree);

try{
    var applyResult = jsonPatch.apply(serverTree, clientTreeChanges);    
    console.log(applyResult === true ? "Changes made without errors" : "Apply returned; " + JSON.stringify(applyResult));
} catch(err){
    console.log(err);
}
```

In my case where comparisons between tree snapshots are used to track modifications of the tree, this means that clients making patches against their local partial tree which generate 'add' events at the root are causing the whole tree to be replaced by a single patch and not having their 'add' patches thrown back as invalid where the server tree already contains something at that path. 

In the meantime I'll look into a workaround, applying adds to an empty tree, then merging the two trees before applying remove or replace operations.

**Comment by tomalec** [comment]
According to [JSON-Patch spec](https://tools.ietf.org/html/rfc6902#section-4.1):
> If the target location specifies an object member that does exist,
      that member's value is replaced.

So I would say it's desired specified behavior, and should not throw an error.

You can always add `test` operation before.

If you would like to, keep your distributed trees in sync, especially while networking, I strongly suggest you JSON Patch OT:
https://github.com/PuppetJs/JSON-Patch-OT
https://github.com/PuppetJs/JSON-Patch-OT-agent
Unfortunately, we lack nice project page, (as mentioned at)
But I hope you can get some overview from a https://youtu.be/bTG7pIyzr7A
