### ISSUE TITLE
Usage with angular

### ISSUE THREAD

**Issue by davidleureka** [Starcounter-Jack/JSON-Patch#95]
Like the project, very useful. But I have one questions related to using it with angular. Angular tends to added its own properties (e.g. $promise and $resolved) to its model objects as you work with them in the UI. This means that your patch will often contain things like:

```
[  
   {  
      "op": "add",
      "path": "/$promise",
      "value": "abc"
   },
   {  
      "op": "add",
      "path": "/$resolved",
      "value": true
   }
]
```

which must be stripped out before you send a PATCH to your services. Is there any good way to prevent the observer from logging changes to these things?

**Comment by warpech** [comment]
We use this library in  PuppetJs, and this is how we filter patches:

https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L525-L536

Basically, you need to handle this outside.

**Comment by anjo** [comment]
We're doing this in a patch

@@ -347,6 +339,7 @@ var jsonpatch;
         for (var t = oldKeys.length - 1; t >= 0; t--) {
             var key = oldKeys[t];
             var oldVal = mirror[key];
+            if(key.indexOf("$") == 0) continue;
             if (obj.hasOwnProperty(key) && !(obj[key] === undefined && _isArray(obj) === false)) {
                 var newVal = obj[key];
                 if (typeof oldVal == "object" && oldVal != null && typeof newVal == "object" && newVal != null) {
@@ -369,6 +362,7 @@ var jsonpatch;
         }
         for (var t = 0; t < newKeys.length; t++) {
             var key = newKeys[t];
+            if(key.indexOf("$") == 0) continue;
             if (!mirror.hasOwnProperty(key) && obj[key] !== undefined) {
                 patches.push({ op: "add", path: path + "/" + escapePathComponent(key), value: deepClone(obj[key]) });
             }

**Comment by tomalec** [comment]
We cannot hard-code such check, as many other project uses properties with `$` in name as any other.

I would also advise either filter it by yourself or use external library that does it for you (like https://github.com/PuppetJs/PuppetJs)

**Comment by tomalec** [comment]
I closed the issue, as the OP is pretty old and I hope it's answered. If not, please feel free to re-open.
//cc @davidleureka
