### ISSUE TITLE
Move the event-based trigger of dirty checking outside of JSON-Patch

### ISSUE THREAD

**Issue by warpech** [Starcounter-Jack/JSON-Patch#99]
In spirit of https://github.com/Starcounter-Jack/JSON-Patch/issues/88#issuecomment-173644497, I think that the best way to trigger dirty checking would be to actually move it out of JSON-Patch.

In our use case, it should be moved to https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet-dom.js.

The code in Puppet DOM will trigger `jsonpatch.generate(puppet.observer)` from the outside on certain DOM events (`mouseup`, `keyup`). There will be only single call (setTimeout `0`), instead of current [interval calls](https://github.com/Starcounter-Jack/JSON-Patch/blob/6a339cc0c4ffb296e8e816f151530f1f6c2350cc/src/json-patch-duplex.ts#L327).

This could be celebrated by giving it a 1.0.0 number (https://github.com/Starcounter-Jack/JSON-Patch/issues/80)

@tomalec, @miyconst WDYT?

**Comment by warpech** [comment]
In a nutshell it means move `jsonpatch.observe` and `jsonpatch.unobserve` to Puppet DOM. 

The beauty of it is that it can be done in steps:

1. Make the new implementation in Puppet DOM and switch to use it instead of `jsonpatch.observe` and `jsonpatch.unobserve`
2. Remove `jsonpatch.observe` and `jsonpatch.unobserve` from JSON-Patch

**Comment by tomalec** [comment]
LGTM :)

Maybe, we could also provide tiny library (as a migration helper) for those who currently use `jsonpatch.observe` and `jsonpatch.unobserve` without Puppet.

**Comment by warpech** [comment]
Plan for development:

1. prepare PuppetJs changes in PuppetJs branch `dirty-checking-refactor-json-patch-issue-99`:
 - stop using `jsonpatch.observe` and `jsonpatch.unobserve`
 - add `jsonpatch.generate` calls in new event handlers in `puppet-dom.js`
2. include changes in Starcounter nightly
3. prepare JSON-Patch changes in JSON-Patch branch `dirty-checking-refactor-json-patch-issue-99`
4. release new version of JSON-Patch
5. release new version of PuppetJs
6. include changes in Starcounter nightly

**Comment by warpech** [comment]
Assigning to @aloscha

**Comment by warpech** [comment]
Just discussed with @tomalec and @aloscha that this doesn't make much sense, because https://github.com/Starcounter-Jack/JSON-Patch/issues/96 will change it again. Closing.
